# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
version: '3'

services:
  suitecrm-mariadb:
    container_name: suitecrm-mariadb
    image: docker.io/bitnami/mariadb:11.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - 'suitecrm_mariadb_data:/bitnami/mariadb'
    networks:
      - suitecrm-network
    restart: unless-stopped

  suitecrm:
    container_name: suitecrm
    image: docker.io/bitnami/suitecrm:8
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=${MARIADB_USER}
      - SUITECRM_DATABASE_NAME=${MARIADB_DATABASE}
      - SUITECRM_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'suitecrm_data:/bitnami/suitecrm'
    networks:
      - suitecrm-network
    depends_on:
      - suitecrm-mariadb
    restart: unless-stopped

volumes:
  suitecrm_mariadb_data:
  suitecrm_data:
  certbot-etc:

networks:
  suitecrm-network:
    driver: bridge
